import React, { useEffect, useState } from 'react';

const TermsofService = (props) => {
    return (
        <div className="legal">
            <h1>Bobble Sports Terms of Service</h1>
            <p>Last updated on August 9, 2020</p>
            <p>This Bobble Sports Terms of Service (the “TOS”) applies to the Website Bobble Sports.com, referred to as Bobble Sports (“Boo The Stros,” “we,” “us” or “our”) as listed below. If you have any questions or concerns regarding this TOS, please contact us first at <span style={{textDecoration:"underline"}}>privacy@Bobble Sports.com</span>.</p>  
            <p>You agree to the TOS, in its entirety, when you: (a) access the Site or use it’s Services. <span style={{fontWeight: "800"}}>IF YOU DO NOT AGREE TO THIS TOS IN ITS ENTIRETY, YOU SHOULD NOT ACCESS OR OTHERWISE USE THE SITE OR SERVICES</span>.</p>
            <h2>Changes</h2>
            <p style={{fontWeight:"800"}}>Please read this page carefully. Bobble Sports may revise these TOS at any time, without prior notice, by updating this posting. You should visit this page periodically to review the TOS, because THEY ARE BINDING on you.</p>
            <h2>Use of Material</h2>
            <p>Bobble Sports authorizes you to view ("Website") solely for your personal, noncommercial use. Special rules may apply to the use of certain software and other items provided on the Website. Any such special rules are listed as "Legal Notices" on this Website and are incorporated into this Agreement by reference.</p>
            <p>The contents of this Website, such as text, graphics, images and other material ("Material"), are protected by copyright under both United States and foreign laws. Unauthorized use of the Material may violate copyright, trademark, and other laws. You must retain all copyright and other proprietary notices contained in the original Material on any copy you make of the Material. You may not sell or modify the Material or reproduce, display, publicly perform, distribute, or otherwise use the Material in any way for any public or commercial purpose. The use of the Material on any other Website or in a networked computer environment for any purpose is prohibited.</p>
            <p>If you violate any of these Terms, your permission to use the Material automatically terminates and you must immediately destroy any copies you have made of the Material.</p>
            <h2>Age Restrictions</h2>
            <p>Certain content within Bobble Sports may not be suitable for children and, in this regard, we advise parental guidance. If you are under [16], you must read these Terms with your parent or guardian prior to using Bobble Sports, as your use of Bobble Sports shall be confirmation that you and your parent or guardian understand and agree to these Terms.</p>
            <p>If we reasonably believe that you have not told us your true age, we may suspend your use of Bobble Sports until you have provided proof acceptable to us.</p>
            <h2>Liability</h2>
            <p>The Material may contain inaccuracies or typographical errors. Bobble Sports makes NO representations about the accuracy, reliability, completeness, or timeliness of the Material or about the results to be obtained from using the Website and the Material. Your use of this Website and any included Material is at your own risk. Changes are periodically made to the Website and may be made at any time.</p>
            <p style={{fontWeight:"800"}}>Bobble Sports does not warrant that the website will operate error-free or that this website and its server are free of computer viruses and other harmful goods. If your use of the website or the material results in the need for servicing or replacing equipment or data, Bobble Sports is not responsible.</p>
            <p style={{fontWeight:"800"}}>The website and material are provided on an "as is" basis without any warranties of any kind. Bobble Sports and its suppliers, to the fullest extent permitted by law, disclaim all warranties, including the merchantability, fitness for particular purpose, and non-infringement of third parties rights. Bobble Sports and its suppliers make no warranties about the completeness, accuracy, reliability, or timeliness of the material, services, software text, graphics, and links.</p>
            <h2>Disclaimer of Consequential Damages</h2>
            <p style={{fontWeight:"800"}}>IN NO EVENT, SHALL Bobble Sports, ITS SUPPLIERS, OR ANY THIRD PARTIES MENTIONED ON THIS SITE BE LIABLE FOR ANY DAMAGES WHATSOEVER (INCLUDING, WITHOUT LIMITATION, INCIDENTAL AND CONSEQUENTIAL DAMAGES, LOST PROFITS, OR DAMAGES RESULTING FROM LOST DATA OR BUSINESS INTERRUPTION) RESULTING FROM THE USE OR INABILITY TO USE THE WEBSITE AND THE MATERIAL, WHETHER BASED ON WARRANTY, CONTRACT, TORT, OR ANY OTHER LEGAL THEORY, AND WHETHER OR NOT Bobble Sports IS ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.</p>
            <h2>User Submissions</h2>
            <p>In the event the Website allows submissions or posting, any communication which you post, email, submit, forward, suggest, supply or request to be posted to the Website is considered to be non-confidential. By posting communications to the Website, you automatically grant Bobble Sports a royalty-free, perpetual, irrevocable nonexclusive license to use, reproduce, modify, publish, edit, translate, distribute, perform, and display the communication alone or as part of other works in any form, media, or technology whether now known or hereafter developed, and to sublicense such rights through multiple tiers of sub licensees.</p>
            <p>As a User, you are responsible for your own communications and are responsible for the consequences of their posting. You must not do the following things: Post material that is copyrighted, unless you are the copyright owner or have the permission of the copyright owner to post it; post material that reveals trade secrets, unless you own them or have the permission of the owner; post material that infringes on any other intellectual property rights of others or on the privacy or publicity rights of others; post material that is obscene, defamatory, threatening, harassing, abusive, hateful, or embarrassing to another User or any other person or entity; post a sexually-explicit image; post advertisements or solicitations of business; post chain letters or pyramid schemes; or impersonate another person.</p>
            <p>Bobble Sports does not represent or guarantee the truthfulness, accuracy, or reliability of any of communications posted by other Users or endorse any opinions expressed by Users. You acknowledge that any reliance on material posted by other Users will be at your own risk.</p>
            <p>Bobble Sports does not screen communications in advance and is not responsible for screening or monitoring material posted by Users. If notified by a User of communications which allegedly do not conform to this Agreement, Bobble Sports may investigate the allegation and determine in good faith and its sole discretion whether to remove or request the removal of the communication. Bobble Sports has no liability or responsibility to Users for performance or nonperformance of such activities. Bobble Sports reserves the right to expel Users and prevent their further access to the Website for violating this Agreement or the law and the right to remove communications which are abusive, illegal, or disruptive.</p>
            <h2>Links to Other Sites</h2>
            <p>The Website may contain links to third party Websites. These links are provided solely as a convenience to you and NOT as an endorsement by Bobble Sports of the contents on such third-party Websites. Bobble Sports is NOT responsible for the content of linked third-party sites and does not make any representations regarding the content or accuracy of materials on such third party Websites. If you decide to access linked third-party Websites, you do so AT YOUR OWN RISK.</p>
            <h2>Software Licenses</h2>
            <p>All software that is, or may be, made available for downloading from the Website ("Software") is protected by copyright and may be protected by other rights. The use of such software is governed by the terms of the software license agreement or designated "Legal Notice" accompanying such software ("License Agreement"). The downloading and use of such software is conditioned on your agreement to be bound by the terms of the License Agreement.</p>
            <h2>Limitation of Liability</h2>
            <p>Unless otherwise expressly provided in a Software License or Legal Notice, the aggregate liability for Bobble Sports to any/all users for any/all claims arising from the use of the Copyrighted Materials on this website is limited to $.01 US (one cent, one penny, 1/100 of a dollar, US)</p>
            <h2>Indemnity</h2>
            <p>You agree to defend, indemnify, and hold harmless Bobble Sports, its officers, directors, employees and agents, from and against any claims, actions or demands, including without limitation reasonable legal and accounting fees, alleging or resulting from your use of the Material (including Software) or your breach of the terms of this Agreement. Bobble Sports shall provide notice to you promptly of any such claim, suit, or proceeding and shall assist you, at your expense, in defending any such claim, suit or proceeding.</p>
            <h2>Export Control</h2>
            <p>The United States controls the export of products and information. You agree to comply with such restrictions and not to export or re-export the Materials (including Software) to countries or persons prohibited under the export control laws. By downloading the Materials (including Software), you are agreeing that you are not in a country where such export is prohibited or are a person or entity to which such export is prohibited. You are responsible for compliance with the laws of your local jurisdiction regarding the import, export, or re-export of the Product.</p>
            <h2>User Information</h2>
            <p>Our Privacy Policy at www.Bobble Sports.com/privacy explains how we use any information about you that we receive from you or collect when you use Bobble Sports.</p>
            <h2>General</h2>
            <p>This Website is hosted on a web server in the continental USA. Bobble Sports makes no claims the Materials are appropriate or may be downloaded outside of the United States. Access to the Materials (including Software) may not be legal by certain persons or in certain countries. If you access the Website from outside of the United States, you do so at YOUR OWN RISK and are responsible for compliance with the laws of your jurisdiction. This Agreement is governed by the internal substantive laws of the State of California, without respect to its conflict of laws principles.</p>
            <p>If the need arises, we may suspend access to Bobble Sports to carry out routine or emergency work. We will not be responsible if for any reason Bobble Sports is unavailable.</p>
            <p>If any provision of this Agreement is found to be invalid by any court having competent jurisdiction, the invalidity of such provision shall not affect the validity of the remaining provisions of this Agreement, which shall remain in full force and effect. No waiver of any term of this Agreement shall be deemed a further or continuing waiver of such term or any other term. Except as expressly provided in a particular "Legal Notice" or Software License or material on particular Web pages, this Agreement constitutes the entire Agreement between you and Bobble Sports with respect to the use of Website. Any changes to this Agreement must be made in writing, signed by an authorized representative of Bobble Sports.</p>
        </div>
    );
};

export default TermsofService;